const anna = new Person('Anna', 'Karutina')
console.log(anna)
anna.greeting()
anna.setAge(25)
console.log(anna.getAge())
const urmas = new Person('Urmas', 'Voevodin')
console.log(urmas)
urmas.greeting()
